name: Tests

on: ["push"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2
      - uses: php-actions/composer@v5
      - uses: NWBY/pest-action@v1.2.0
